name: Fetch translations

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger pull request
        uses: Andreassim/LokaliseAction@v1.16
        with:
          LOKALISE_API_KEY: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_KEY: ${{ secrets.LOKALISE_PROJECT_TOKEN }}
        
